[package]
name = "unipept"
version = "0.1.0"
authors = ["Felix Van der Jeugt <felix.vanderjeugt@gmail.com>",
           "Stijn Seghers <stijn.seghers@gmail.com>"]

[dependencies]
clap = "2.3.0"
csv = "0.15"
fst = "0.1"
regex = "0.2.1"
ordered-float = "0.4.0"
error-chain = "0.10.0"
